### ISSUE TITLE
GetUVMap Node doesn't working?

### ISSUE THREAD

**Issue by tompsono** [3DSinghVFX/animation_nodes#130]
<img width="442" alt="2020-02-28 141741" src="https://user-images.githubusercontent.com/37116084/75512546-2a707100-5a35-11ea-8cdd-974ccfadef5e.png">

In daily build 25-02-2020.

GetUVMap Node doesn't working?
What uv name should I enter?
I tested in Blender 2.80.75 and 2.82.6

**Comment by 3DSinghVFX** [comment]
Hi...
It is working fine. By default, the _Mesh Object Input_ node does not load the UV map (also the Vertex Color). So, open the properties panel (N-panel), unhide the _Load UVs_ input and enable it.

![Screenshot from 2020-02-28 11-17-31](https://user-images.githubusercontent.com/30294746/75513964-55020000-5a1c-11ea-9a99-09ad32142015.png)

**Comment by tompsono** [comment]
Sorry,I missed that.
Thanks for your replying :)
