### ISSUE TITLE
Crash on MacOS while exporting alembic

### ISSUE THREAD

**Issue by df-0** [3DSinghVFX/animation_nodes#138]
Repeated crash while exporting alembic (happened 3 times out of 3). Node network works correctly in viewport, whether playing back linearly or jumping around the timeline. Crash log and node network screenshot attached.
<img width="1910" alt="Screenshot 2020-03-25 at 17 39 21" src="https://user-images.githubusercontent.com/16046786/77568055-f2d3d800-6ebf-11ea-8d66-b1d9d141753b.png">

(https://github.com/3DSinghVFX/animation_nodes/files/4382419/alembicCrashLog.txt)

**Comment by 3DSinghVFX** [comment]
Sorry for the late reply. Please try the latest version of AN or AN+EN, it is fixed in https://github.com/JacquesLucke/animation_nodes/pull/1294.

**Comment by 3DSinghVFX** [comment]
You can download the latest version of AN: https://animation-nodes.com/
AN+EN: https://blender.community/c/graphicall/

**Comment by df-0** [comment]
Exported the same file without difficulty using the current version (listed as 2.1.7 in the addons window, is there a better way of checking?). Works great! Thanks!

**Comment by 3DSinghVFX** [comment]
You can check the _[CHANGELOG.md](https://github.com/JacquesLucke/animation_nodes/blob/master/CHANGELOG.md)_ file for updates. BTW, I also update the build and the log on the graphicall site when any changes happen to AN or AN+EN: https://blender.community/c/graphicall/tdbbbc/
