### ISSUE TITLE
Possible to add "Matrices"  to the "Mesh Points Scatter" node

### ISSUE THREAD

**Issue by kdsin23** [3DSinghVFX/animation_nodes#147]
Hi,is it possible to add "Matrices" output to the "Mesh Points Scatter" node like the  "distribute matrix" node, i think if possible,we can save some times to convert points locations to matrices.Thank you!

**Comment by kdsin23** [comment]
please close this topic, Thank you!

**Comment by 3DSinghVFX** [comment]
Okay.It will be added soon.
