### ISSUE TITLE
I can't install animation node

### ISSUE THREAD

**Issue by pirtoda** [3DSinghVFX/animation_nodes#148]
I have win 10 v 1909 32 bit +blender 2.80 32bit +blender 2.79 (both) 
I download addond Animation Nodes from many palces here and  and from "animation-nodes.com" and from "cgmatter.com"
try in other windows 10 v 1509 
try unistall and install  c++Redistribuable Visual 2015-2019 two times 
all give the same mssage when click to active the addon  "traceback (most recent call last)
![2 80](https://user-images.githubusercontent.com/66679634/84149879-09b6af00-aa59-11ea-86fd-bc4262d3a4fc.jpg)
![2 79](https://user-images.githubusercontent.com/66679634/84149888-0b807280-aa59-11ea-9ca3-61fecd13552e.jpg)

**Comment by 3DSinghVFX** [comment]
Hi...
Blender2.8x:
Did you install `vc_redist.x64` from [Microsoft Center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2)?

Blender2.79:
You can download the latest Animation Nodes' build for Blender2.79 from https://animation-nodes.com/

_Please remove old Animation Nodes' files from the addon folder before installing the new one._
