### ISSUE TITLE
request and question about close packing node.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [3DSinghVFX/animation_nodes#149]
Thanks for making this "close packing" node, it's very amazing, but I have some request and questions.
1. a request is to change the default value of close packing nodes.
this node sets the radius of the object. I think it's reasonable to make the radius starts at 1 instead of 0.1 currently. because I am essentially use my original model that has a scale of 1,1,1 as a reference for the effect (specifically the relaxation method). As the default value of radius is 0.1 now, I have to change that every time which turns to be a little annoying.
I understand this maybe a very minor request, but I think it's reasonable. Many other nodes in AN also has an intention to keep the scale starting at 1,1,1, such as many modes of "distribute matrices node" (true, the spiral mode is an exception for its own reasons). I think keep consistency is important.

2. I have an attached node tree. the margin is made extremely small,
but the objects aren't allowed to get even closer even if I asked them to do so.
It seems the "repulsion factor" turns to be the value that will help allow objects get even closer, but such a value is very abstract to me. 
![example](https://user-images.githubusercontent.com/55994236/84801053-faa6a280-affe-11ea-9a41-7db5efb56c9f.png)

I have provided an design example of C4D's push apart effector. it has options like "radius" (decides the size of protective bubble that prevent intersection), and "iterations" (determines the accuracy of its algorithm).
![PAE](https://user-images.githubusercontent.com/55994236/84801152-1c078e80-afff-11ea-8f11-7f38a33270b6.png)
I suppose their functions are comparable to "margin" and "repulsion factors" respectively, but I am very confused with "margin" and "repulsion factor" and their relationship.
Thus, basically my questions are the following, and they are somehow related to each other.
1. Why taken the margin low doesn't help my objects get closer?
2. What does repulsion factor really means with its value?
3. How these two values actually interact with each others?

Thanks in advance for reading and answering the questions.

**Comment by 3DSinghVFX** [comment]
Hi :)
You're welcome, and thanks for the feedback.

>     1. a request is to change the default value of close packing nodes.
>        this node sets the radius of the object. I think it's reasonable to ...

You are right, I'll change the default values for all methods.

>     2. I have an attached node tree. the margin is made extremely small,
>         but the objects aren't allowed to get even closer even if I asked them to do so...

Here is the explanation for margin:
![Margin](https://user-images.githubusercontent.com/30294746/84808251-0e193400-b026-11ea-88e0-d22b796fa841.png)


> * Why taken the margin low doesn't help my objects get closer?

The reason for that is I have not implemented the attraction force. So, the margin will be effective when two points A, B has distance < radiusA + radiusB + margin.

> * What does the repulsion factor really means with its value?

The _Repulsion Factor_ basically controls the magnitude of the repulsion force.

> * How these two values actually interact with each others?

They are independent of each other.

In your case, points/spheres are not coming close because they are already not overlapping, and there is no attraction force. So, to bring them close, just decrease the separation input points:
![screen](https://user-images.githubusercontent.com/30294746/84810008-5b96a080-b028-11ea-821f-e637b3431ab2.png)

> I have provided an design example of C4D's push apart effector. it has options like "radius" (decides the size of protective bubble that prevent intersection), and "iterations" (determines the accuracy of its algorithm).

Thanks, I'm aware of that.
- The `Radius+Margin` input of _Close Packing_ node act as a protective bubble.
- `Error Max and Iterations Max` When algorithm achieves the _Error Max_ then it will stop otherwise it will run _Iterarions Max_ times. 
![Screenshot from 2020-06-16 23-42-56](https://user-images.githubusercontent.com/30294746/84812216-ad8cf580-b02b-11ea-9f44-6e71c614d75a.png)


The _Relaxation Method_ is lack of some features:
1. Attraction Force.
2. Both forces together.
3. Smooth separation or attraction*.
4. Packing based on input weight*.

Feel free to give feedback :)

**Comment by Gerstmann-Bradley** [comment]
> In your case, points/spheres are not coming close because they are already not overlapping, and there is no attraction force. So, to bring them close, just decrease the separation input points:
> ![screen](https://user-images.githubusercontent.com/30294746/84810008-5b96a080-b028-11ea-821f-e637b3431ab2.png)

That's actually what I did, as you can see in my distribute matrices node the width is set very very low, but unfortunately it doesn't help. Objects will be repelled as I decrease the value, hence I was asking these questions. So I have taken another look to that and realize something interesting. I am not sure if I understand the situation well, so I will post the things I did here:

**1**. I generated a sphere, in Edit mode, I scaled the sphere by 0.5, so the sphere has a dimension of 1,1,1 meter (while the scale is 1,1,1 as well). It means my sphere is not default sphere! (If it's a default sphere, it will work well)
**2**. The radius will determine the size of my sphere, if I wish to keep all sphere with a dimension of 1,1,1 (meter), then the radius is kept 1.
**3**. Just Decrease the width (&/length) is not helping situation, the sphere will be repelled.
A) In addition to a low enough width &/ length, decrease margin won't help.
B) In addition to ~ , decrease the repulsion factor will help, but only if it becomes incredibly low like 0.005.

I have tried this with newest AN & blender 2.83. This issue should be replicable. (windows 10)
I am not sure how should I interpret this phenomenon about why it happens. Maybe you can solve my question. Thanks a lot!

**Comment by 3DSinghVFX** [comment]
> > In your case, points/spheres are not coming close because they are already not overlapping, and there is no attraction force. So, to bring them close, just decrease the separation input points:
> > ![screen](https://user-images.githubusercontent.com/30294746/84810008-5b96a080-b028-11ea-821f-e637b3431ab2.png)
>
> That's actually what I did, as you can see in my distribute matrices node the width is set very very low, but unfortunately it doesn't help. Objects will be repelled as I decrease the value, hence I was asking these questions. So I have taken another look to that and realize something interesting. I am not sure if I understand the situation well, so I will post the things I did here:

Let me first explain the _Radius_ and Margin:
**Radius** is the radius of a protective bubble around a point _(note the green Viewer node)_.
![ClosePackingNodeDemo1](https://user-images.githubusercontent.com/30294746/84930907-9b748b00-b0ef-11ea-8fdd-b31444f793d8.png)

 **Margin** is the distance between two bubbles' surface that you want to maintain _(note the green Viewer node)_.
![ClosePackingNodeDemo2](https://user-images.githubusercontent.com/30294746/84930948-a92a1080-b0ef-11ea-9b93-69ec86f637a2.png)

> **1**. I generated a sphere, in Edit mode, I scaled the sphere by 0.5, so the sphere has a dimension of 1,1,1 meter (while the scale is 1,1,1 as well). It means my sphere is not default sphere! (If it's a default sphere, it will work well)
> **2**. The radius will determine the size of my sphere, if I wish to keep all sphere with a dimension of 1,1,1 (meter), then the radius is kept 1.

In that case (when an object is edited), you can use only the locations from the _Close Packing_ node, 
![ClosePackingNodeDemo3](https://user-images.githubusercontent.com/30294746/84930977-b515d280-b0ef-11ea-982d-48696a7aebcb.png)

**Or** input the exact radius of the object into the _Close Packing_ node (then use _Margin_ if required).
![ClosePackingNodeDemo4](https://user-images.githubusercontent.com/30294746/84930992-bc3ce080-b0ef-11ea-9989-f005956e5777.png)

> **3**. Just Decrease the width (&/length) is not helping situation, the sphere will be repelled.
> A) In addition to a low enough width &/ length, decrease margin won't help.
> B) In addition to ~ , decrease the repulsion factor will help, but only if it becomes incredibly low like 0.005.
> 
> I have tried this with newest AN & blender 2.83. This issue should be replicable. (windows 10)
> I am not sure how should I interpret this phenomenon about why it happens. Maybe you can solve my question. Thanks a lot!

This is happening because of scale != radius or in other words node does not know the exact radius of the object. I'll try to fix that.

If you still have any confusion/queries/suggestion please let me know.
Blend Files:
[ClosePackingDemoFiles.zip](https://github.com/3DSinghVFX/animation_nodes/files/4794214/ClosePackingDemoFiles.zip)

**Comment by Gerstmann-Bradley** [comment]
> If you still have any confusion/queries/suggestion please let me know.
> Blend Files:
> [ClosePackingDemoFiles.zip](https://github.com/3DSinghVFX/animation_nodes/files/4794214/ClosePackingDemoFiles.zip)

OMG, thanks for such detailed answers. My whole point is just to report that and request some other changes, I think as long as you are aware of this issue and has intention to fix them then it may be fine. Thanks a lot!

Just some proposals that may or may not related to this issue:
1. In terms of your previous addition of error max and iteration, it's good to add them, but many times people may not use that often, even now without them the close packing node already works kind of nice. **My suggestion is to hide these socket by default**. Examples are "mesh object input" node, in which you have lots of socket that doesn't show up by default when called.
The purpose doing that is to keep the functionality, while it also makes the UI simpler and cleaner for the user.

2. (still thinking; may added later or not)

**Comment by Gerstmann-Bradley** [comment]
2. I think the issue is that the "radius of protective bubbles" and "scale of the matrix" should not be considered the same thing.

**A)** One thing I am thinking is **not to use "close packing" node to "set scale on purpose"**. The matrix should be generated with a default scale "1,1,1", just as most modes in "distribute matrices" node.
Sure, dynamic radius node will retain the ability to "change the scales" of matrices, but I think they are two different things for distinctive purposes. Because "changing scale" is to avoid intersection, but "setting scale on purpose" seems redundant/unnecessary to "close packing" node.
Also one reference that can be mentioned, is that C4D's "push apart effector" only sets the protective bubble, and is not used to set scale of objects. The scale of objects will retain a default value of 1,1,1, Or you have to change it elsewhere.

**B)** Moreover, I come up another question: doesn't "protective bubble" (I mean the "radius" here should have nothing to do with the scale) and "margin" concept overlaps at some point? If I want to keep the object 200 meters away, either I set two objects's bubble with radius of 100 m, or their margin be 100 m.

At the end, I think just **keep "margin" is sufficient enough for the function of avoiding intersection**. While the default matrices will be generated with a default scale of 1,1,1, and it's not necessary to have the node to set the scale. The scale should only be changed according to the algorithm of "dynamic radius" mode, but it shall be done in the background, and has nothing to do with the users (including me).

Above are Just my personal opinions. Thanks for reading and your patience.

**Comment by 3DSinghVFX** [comment]
>     1. In terms of your previous addition of error max and iteration, it's good to add them, but many times people may not use that often, even now without them the close packing node already works kind of nice. **My suggestion is to hide these socket by default**. Examples are "mesh object input" node, in which you have lots of socket that doesn't show up by default when called.
>        The purpose of doing that is to keep the functionality, while it also makes the UI simpler and cleaner for the user.

I have have made those changes, will be added in upcoming updates:
![Screenshot from 2020-06-18 11-13-56](https://user-images.githubusercontent.com/30294746/84982683-d6f57080-b154-11ea-85d8-b78aeb07f2f0.png)


> **A)** One thing I am thinking is **not to use "close packing" node to "set scale on purpose"**. The matrix should be generated with a default scale "1,1,1", just as most modes in "distribute matrices" node.
> Sure, dynamic radius node will retain the ability to "change the scales" of matrices, but I think they are two different things for distinctive purposes. Because "changing scale" is to avoid intersection, but "setting scale on purpose" seems redundant/unnecessary to "close packing" node.
> Also one reference that can be mentioned, is that C4D's "push apart effector" only sets the protective bubble, and is not used to set scale of objects. The scale of objects will retain a default value of 1,1,1, Or you have to change it elsewhere.

I'm testing new _Object Radius_ input, by default, it set to `1`. It will allow the user to define the object radius or radii. This can solve the problem of radius for all methods. Also an option can be added sth like _Use Radius as Scale_ in _Relaxation_ method. 

> **B)** Moreover, I come up another question: doesn't "protective bubble" (I mean the "radius" here should have nothing to do with the scale) and "margin" concept overlaps at some point? If I want to keep the object 200 meters away, either I set two objects's bubble with radius of 100 m, or their margin be 100 m.

> At the end, I think just **keep "margin" is sufficient enough for the function of avoiding intersection**. While the default matrices will be generated with a default scale of 1,1,1, and it's not necessary to have the node to set the scale. The scale should only be changed according to the algorithm of "dynamic radius" mode, but it shall be done in the background, and has nothing to do with the users (including me).

_Margin_ is handy when we supply the exact radius (radii) of the object.

You're welcome :)

**Comment by Gerstmann-Bradley** [comment]
Thanks, I am looking forward to the update. and will report back if I have thoughts/complaints. close for now.

**Comment by 3DSinghVFX** [comment]
> Thanks, I am looking forward to the update. and will report back if I have thoughts/complaints. close for now.

Okay.

**Comment by 3DSinghVFX** [comment]
Hi :)
Here is the final version of _Close Packing_ node:
![Screenshot from 2020-06-23 16-01-23](https://user-images.githubusercontent.com/30294746/85393629-f2a0b280-b56a-11ea-9472-3513603dc60b.png)
![ClosePackingNodeDemo5](https://user-images.githubusercontent.com/30294746/85393635-f46a7600-b56a-11ea-9d9a-cc1778a2b3e2.png)

**Comment by Gerstmann-Bradley** [comment]
Hi, sorry to respond late. I just checked newest version in EN.
They looks nice to me, and the hidden inputs are exactly what I was expecting. Thanks a lot!
Also thanks to add vector and radii output! I think they are really helpful.
The only suggestions will probably be to keep at least "vector" unhidden.
because it maybe useful very often instead of other hidden options. For example frequently I thought to use it to drive "point distance falloff" (this node isn't vectorized unfortunately), and thus I will need a vector output right away. Just my personal opinion.

Again, thanks a lot, if I find any practical issues during actual usage, I will get back to you.

**Comment by 3DSinghVFX** [comment]
You're welcome. Thanks for your feedback.

> The only suggestions will probably be to keep at least "vector" unhidden.
> because it maybe useful very often instead of other hidden options. For example frequently I thought to use it to drive "point distance falloff" (this node isn't vectorized unfortunately), and thus I will need a vector output right away. Just my personal opinion.

That change will be nice.
