### ISSUE TITLE
Auto execute not auto executing

### ISSUE THREAD

**Issue by scorpion451** [3DSinghVFX/animation_nodes#150]
Having a very strange issue that I suspect is related to update calls in some way: 

Everything works fine, except for auto execute and automated updating of nodes and trees after making changes. 

There's two parts to the problem:

### Node trees do not automatically register changes
Changes to a tree will not register until I go to the developer tab, and push the profile button with "update everything" mode selected. No errors are thrown, and the tree executes correctly after this is done- but until I do this, tree changes will not register. This applies to creating connections, cutting connections, and adding new nodes. 

### Auto-Execute does not function
Turning on auto-execute has no effect at all. Executing a tree using the "execute node tree" button works perfectly. The tree does not automatically execute, however, on frame changes, tree changes, property changes, custom triggers, or the "always" setting.

### Standard troubleshooting info and things I've tried:
I am using Blender 2.83, on 64bit Windows 7
The issue does not seem to be present in the vanilla build of animation nodes that came with 2.83, but is present in Extra Nodes.
I have thoroughly checked for old installs, and reinstalled with the newest build of AN: Extra Nodes (the issue was also present in the build of extra nodes I downloaded on the 10th of this month but had not tried to install until today.)
I have the current scene selected in the Animation Node Tree settings panel.
Frame dropping is disabled in playback.
Updating VC_redist.x64 made no difference.

**Comment by scorpion451** [comment]
Update, may be related to not having the latest version of the particle system node tree, which can be found here (and could really use a link somewhere in the docs for extra nodes):
https://drive.google.com/drive/folders/1Lwhzg_acppf0YkYhxJ_a0aUQMQl9aznJ
Example files run correctly, still tinkering to see if I can get my scene running after swapping the new setup into place.

Update 2: nope, still refuses to run any node trees except the example files.
It's like the addon doesn't recognize any scene except the specific one in that file.

Update 3: Tracked down the issue! 

Ironically, it seems the problem is a defective debugging protocol in the addon: 
If any of the node trees that blender loads on start up have issues (for instance, the outdated node tree in my default startup file), the addon terminates the entire auto-execute system, and refuses to reactivate it until blender has been shut down and reopened using a file that does not contain any problematic node trees.

Figure out a way to strip that out and it should be good to go.

**Comment by 3DSinghVFX** [comment]
Hi...
First of all thanks for the feedback. Let me divide this problem into cases 1) General node-tree and 2) Node-tree of the particles-nodes.

- **General node-tree** I have done some tests with the build available on [graphicall](https://blender.community/c/graphicall/tdbbbc/) for Linux. It is working fine for _all the Auto Execution options_.
  Can you please add a file that has the problem.

- **Node-tree of the particles-nodes** In those examples, for better particle-simulation results (and also this is way simulation works) only the `Frame Changed` option is enabled. Another thing is I have added a script that clears the particle cache (that blender does not do) the first frame so that you can view the behaviour of particle with the change of node-tree while simulating.

  I have also mentioned these points in [particles tutorials](https://www.youtube.com/3DSinghVFX) as well. So, if you want to append particles, please append the node-tree and script. I'll also try to replace the script with other nodes.

> Update, may be related to not having the latest version of the particle system node tree, which can be found here (and could really use a link somewhere in the docs for extra nodes): https://drive.google.com/drive/folders/1Lwhzg_acppf0YkYhxJ_a0aUQMQl9aznJ

I'll try to update the docs as soon as possible.

**Comment by scorpion451** [comment]
Okay, here's one that does it:
https://drive.google.com/file/d/1GXO4IPZ0HEQZyPBQFdUshj-7KK0U35oA/view?usp=sharing

there are three node trees present in the file:
* "Node_Setup_For_JUGAAD_ParticleSystem" Your particle system, with some edits and additions of my own. This tree functions without issue.
* "node tree" is a generic tree that displays a vector point using the 3d viewer for testing purposes. This tree functions without issue.
* "Utilities", is a collection of subprograms I had in my startup file. It has been broken by updates and does not function. Having this file present on startup causes the shutdown of auto-execute and automatic tree updates.

Removing this and a couple similar trees from my startup file solved the issue short-term, but I'd call that more a workaround than a true solution like allowing Auto-Execute to resume without a restart after the problem trees have been removed.

To replicate the issue:

1. Open the file directly, so that blender loads from it.
-- Optional 1.5: try to execute node tree, get the expected series of errors caused by broken Utilities file. The issue happens with or without doing this, however: so long as Utilities is present on startup, auto-execute and tree updates will break silently.
2. Immediately remove "Utilities" without attempting to execute animation nodes.
-- Auto-execute does not resume function, and nodes/node trees will not automatically register changes.
3. Attempt to run node tree via "execute node tree"
-- Tree does not run.
4. Profile node tree in "update everything" mode
5. then attempt to run node tree via "execute node tree"
-- Tree will execute once. Auto-execute does not resume function, and nodes/node trees will not automatically register changes without using profile in update everything mode.
6. Save a copy without the "Utilities" tree, and open this new file without closing blender.
9. repeat steps 3-5, should get same results
10. Close blender without saving any changes, and reopen the copy without "Utilities".
11. Animation nodes will run auto-execute and update trees properly.

**Comment by 3DSinghVFX** [comment]
@scorpion451 Thanks. I can regenerate the issue. We will look into that.

If you want to resolve it manually, in the _Utilities_ node-tree there is an _Expression Node_ without an output socket that causes the problem. If you remove that it and reopen the file will fix the problem.
![Screenshot from 2020-06-27 10-35-14](https://user-images.githubusercontent.com/30294746/85917618-45cf7980-b879-11ea-82b2-e2107192d684.png)
![Screenshot from 2020-06-27 10-35-35](https://user-images.githubusercontent.com/30294746/85917619-4b2cc400-b879-11ea-80c4-f817cd4d8850.png)

**Comment by scorpion451** [comment]
Appreciate the bonus bugfix on my file there- had been assuming it was one of my big complicated tangles breaking, and overlooking the abandoned experiment in adding a custom socket type sitting off to one side.
