### ISSUE TITLE
requesting a Global or Local Position in Object Transforms Input node.

### ISSUE THREAD

**Issue by cgndev** [3DSinghVFX/animation_nodes#151]
![KakaoTalk_20200715_140135395](https://user-images.githubusercontent.com/2674360/87505973-320f7a00-c6a5-11ea-908a-46b4f53a852c.png)

as you know , location of Object Transforms Input  returns Local Position. It seems need other node or toggle option to get world position without adding vector of parent location.

**Comment by 3DSinghVFX** [comment]
Hi 
I think that feature is already there. The _Object Transform Input_ gives you the local position and _Object Matrix Input_ node gives you global position:
![screen](https://user-images.githubusercontent.com/30294746/87527611-02af3c00-c6aa-11ea-9851-16e91afee595.png)

**Comment by cgndev** [comment]
Thank for your reply. I think rename node to know clearly..

**Comment by 3DSinghVFX** [comment]
@cgndev You're welcome. We can't change the name because is it will break all old node-trees, and this node gives transformation of object for _World_, _Local_, _Basic_ and _Parent Inverse_ https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/object/matrix_input.html
