### ISSUE TITLE
Where is the find shortest path node?

### ISSUE THREAD

**Issue by derekcbr** [3DSinghVFX/animation_nodes#152]

**Comment by 3DSinghVFX** [comment]
Hi...
It is available in the _Add_ menu, `Add -> Mesh -> Operators -> Find Shortest Path`.

**Comment by derekcbr** [comment]
Thanks! Which python file has this node?

**Comment by 3DSinghVFX** [comment]
It is in the `nodes/mesh` folder: https://github.com/3DSinghVFX/animation_nodes/blob/extranodes/animation_nodes/nodes/mesh/find_shortest_path.py

**Comment by 3DSinghVFX** [comment]
Is it resolved the issue, please let me know?

**Comment by derekcbr** [comment]
def find_lowest_cost_node(costs):
		lowest_cost = float("inf")
		lowest_cost_node = None
		for node in costs:
			cost = costs[node]
			if cost < lowest_cost and node not in processed:
				lowest_cost = cost
				lowest_cost_node = node
		return lowest_cost_node
  
    def dijkstra(costs):
		node = find_lowest_cost_node(costs)
		while node is not None:
			cost = costs[node]
			neighbors = graph[node]
			for n in neighbors.keys():
				new_cost = cost + neighbors[n]
				if costs[n] > new_cost:
					costs[n] = new_cost
					parents[n] = node
			processed.append(node)
			node = find_lowest_cost_node(costs)
	graph = {}
	graph["start"] = {}
	graph["start"]["a"] = 6
	graph["start"]["b"] = 2

--------------

I studied your algorithm and find the result is quite different from the above in python. Can not figure it out why? Thanks!

**Comment by 3DSinghVFX** [comment]
You have processed the node inside the while loop. 
According to the [Dijkstra](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) algorithm, 1) Assign the temporary weights, and make the parent (previous) nodes are undefined. 2) Then reassign the weight of the nodes based on their distance/cost and update the parent nodes in the while loop. 3) When it is finished, use another loop to construct the path from any node to your start node from the parent nodes.

**Comment by derekcbr** [comment]
Thanks a lot! Always helpful!
