### ISSUE TITLE
About Update of AN+EN build in blender community

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [3DSinghVFX/animation_nodes#153]
Hi,

I suppose the animation-nodes.com doesn't contain Extra nodes build.
So I always download AN+EN from blender community: https://blender.community/c/graphicall/0hbbbc/.
But recently I suppose it's not updating following every commit. Now it shows its last update was on last Sunday, but this week there are more commits being submitted. I guess the reason is that now we have AN for 2.83 LTS and latest AN (that maybe used for further version of blender such as 2.9x?)
I wonder is there a way to easily get most updated version of AN+EN pack?

Thanks.

**Comment by 3DSinghVFX** [comment]
Hi :)

> I suppose the animation-nodes.com doesn't contain Extra nodes build.

Yes, it does not.

> So I always download AN+EN from blender community: https://blender.community/c/graphicall/0hbbbc/.
> But recently I suppose it's not updating following every commit. Now it shows its last update was on last Sunday, but this week there are more commits being submitted. I guess the reason is that now we have AN for 2.83 LTS and latest AN (that maybe used for further version of blender such as 2.9x?)
> I wonder is there a way to easily get most updated version of AN+EN pack?

Actually, when AN+EN LTS release I decided to keep that build on https://blender.community site, and daily/latest build on GitHub.

**Now, I'll upload the daily/latest of AN+EN build on https://blender.community/c/graphicall, and 
AN+EN LTS build on the GitHub https://github.com/3DSinghVFX/animation_nodes/releases.**

However, you can also download all the builds from the release page: https://github.com/3DSinghVFX/animation_nodes/releases

**Comment by 3DSinghVFX** [comment]
@Gerstmann-Bradley AN+EN build is updated: https://blender.community/c/graphicall/0hbbbc/

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley AN+EN build is updated: https://blender.community/c/graphicall/0hbbbc/

Thanks a lot!
