### ISSUE TITLE
Sphere packing points?

### ISSUE THREAD

**Issue by gerroon** [3DSinghVFX/animation_nodes#155]
Hi

I am using the packing node, it is nice but I cant get sphere packing with points to affect the input vertices in any way. Do you have any example of that?

thanks

**Comment by 3DSinghVFX** [comment]
Hi :)

You should use the *Relaxation* method os *Close Packing* node,
![Screenshot from 2020-10-02 19-40-36](https://user-images.githubusercontent.com/30294746/94932916-50885300-04e7-11eb-92f9-d1c520a55b9f.png)

**Comment by gerroon** [comment]
Hi

Thanks for the answers. So the option I mention is non functional as I understand?

**Comment by 3DSinghVFX** [comment]
@gerroon Can you please elaborate on what effect you want to achieve with this node? What do you mean by "*I can't get sphere packing with points to affect the input vertices in any way.*"?
