### ISSUE TITLE
The post in blender community seems not updated well

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [3DSinghVFX/animation_nodes#161]
Hi, 
Referring to https://github.com/JacquesLucke/animation_nodes/issues/1645
I have confirmed that the build provided in blender community post doesn't include simulation nodes.
(https://blender.community/c/graphicall/0hbbbc/)
More importantly the "compare number" node (which is not part of EN) is missing.

I have tried to download directly from github and everything is fine.
I am not sure the reason of breakage as the website is supposed to auto-update itself with the newest commit?
Would you be able to investigate?
Thanks.

**Comment by 3DSinghVFX** [comment]
@Gerstmann-Bradley Thanks for the report. I'll try fix it as soon as possible.
BTW on the blender.community site I have to manually update the builds.

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley Thanks for the report. I'll try fix it as soon as possible.
> BTW on the blender.community site I have to manually update the builds.

got it, no problem.

**Comment by 3DSinghVFX** [comment]
@Gerstmann-Bradley Thanks.
I have updated the builds of AN+EN on the Blender Cummunity which has **Simulation Nodes**.
