### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by bossdown123** [3DSinghVFX/animation_nodes#163]
![image](https://user-images.githubusercontent.com/48166550/109430088-3ed2ab00-79b4-11eb-9b1b-aea60e7c55a5.png)
Animation nodes wont install on 2.93.0

**Comment by 3DSinghVFX** [comment]
Hi. Please try the latest build of [Blender 2.93](https://builder.blender.org/download/) and [AN+EN](https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build).
