### ISSUE TITLE
Set Custom Attribute - Custom Attribute not showing eg on / Attribute Math Node

### ISSUE THREAD

**Issue by mapoart** [3DSinghVFX/animation_nodes#165]
I have compiled the Blender - today morning  and it seems that custom attrs are not showing in the geometry nodes. 

![image](https://user-images.githubusercontent.com/8799218/110094248-e62c5500-7d9b-11eb-8e8e-fe7f6a4b575b.png)

Also there are not on the list: 

![image](https://user-images.githubusercontent.com/8799218/110094363-06f4aa80-7d9c-11eb-8c7e-b859b9f3f65a.png)

Based on the great tutorial: https://www.youtube.com/watch?v=BjrUUX7NW1Y

**Comment by 3DSinghVFX** [comment]
@mapoart Hi. It is working fine on the [latest build of Blender 2.93](https://builder.blender.org/download/),
![Screenshot from 2021-03-05 15-41-10](https://user-images.githubusercontent.com/30294746/110101212-4d143300-7dc9-11eb-9a40-62e77a005beb.png)
![Screenshot from 2021-03-05 15-46-18](https://user-images.githubusercontent.com/30294746/110101756-fb1fdd00-7dc9-11eb-913a-1fca223ebace.png)


Can you please recompile the Blender 2.93?

**Comment by mapoart** [comment]
Yes It works! I have just recompiled (wrote you on YT) and it works!! Thanks!!
