### ISSUE TITLE
missing custom attributes get node

### ISSUE THREAD

**Issue by luckychris** [3DSinghVFX/animation_nodes#167]
i downloaded just a few minutes ago the branch "custom attributes" and compiled it with python 3.9.

Unfortunately i only see the custom attributes set node, but not the get node....

![image](https://user-images.githubusercontent.com/232549/111616830-a4130280-87e2-11eb-9a11-afb2c912b555.png)

**Comment by 3DSinghVFX** [comment]
@luckychris  Hi. You need to download the `extranodes` branch or you can download the compiled build from the [Release Page](https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build). The `custom_attributes` branch is under development and patch for upstream.

**Comment by luckychris** [comment]
thank you - worked
