### ISSUE TITLE
Blender 2.93 Alpha

### ISSUE THREAD

**Issue by mac4kent** [3DSinghVFX/animation_nodes#168]
MacOS 11.3 Beta (20E5217a)
Blender 2.93 Alpha on build
Add-ons is error not work for me.

**Comment by 3DSinghVFX** [comment]
Hi. Can you please attach the error message?

**Comment by mac4kent** [comment]
Sureeeeeeeee
https://youtu.be/f50W9Elg9XE

**Comment by 3DSinghVFX** [comment]
> Sureeeeeeeee
> https://youtu.be/f50W9Elg9XE

It looks like you have installed multi AN versions. So, please remove all the versions then install a fresh one.

**Comment by mac4kent** [comment]
That is not true. not multi. First on Mac install add-ons I know need to fix because of [√]
Other GoZ (GoB), Avastar, and etc they did fixed.
