### ISSUE TITLE
some suggestions...

### ISSUE THREAD

**Issue by Majoran99** [3DSinghVFX/animation_nodes#170]
Thank you a lot for the Extra Nodes, they are very useful for me.
If I may suggest some more nodes…

What Blender/AN still lack are ways to filter / re-organise incoming data. This is especially an issue with sound input. 
For example: From a MIDI file I receive pitch 60 is going to 1 sometimes, remaining there for a few frames and then goes back to 0. 
I want every time it goes to 1 that an action (movement of an object) is triggered, no matter how long then it stays at 1. So only if a 1 is hit after being at 0 before, I want an object to do a movement.
It would be great to have a node that registers such changes.

A related wish: For the duration of pitch 60 being at 1, I would like to have a counter counting up +1 every frame. Say, pitch 60 is normally at 0 but from frame 55 to 75 it is at 1, a counter should start counting on frame 55, until 75. (counter starts at 0, reaching 20.) The node should react on the fact that pitch 60 has hit 1 and stays there for 20 frames.

Next issue (related)… pitch 60 hits 1, an object should then be triggered to do something. Next time pitch 60 hits 1, another object should be triggered. So I would need a counter counting the 1-hits of pitch 60.
(Related: a node that adds up every incoming value per frame.)

Also helpful would be: A node that registers whether an object is moving or not. Which means, the node compares the current location with the previous, whether it is the same or not.

Next..: At some frames, a new random number should be generated. E.g. at frame 55, 100, 222 (or, every time pitch 60 hits 1). The random number would be for example new positions of an object. The problem at status quo is that I can pick out the 55 from the time info and then generate a random number, but it would not stay longer than frame 55. Of course, if I already know exactly that in frame 55, 100 and 222 there should be the new numbers, it is possible. But not flexible; when having a MIDI input I do not know when things happen.
A node that stores a number would be super.

Helpful would also the possibility to compose object names. For example I have empty1, empty2, empty3… etc. and also cube1, cube2, cube3… A node that creates an object list with an number index list as input can be useful.

I know that some of these things are *somehow* realisable in AN, but it`s pretty a hack. For example in this Tut (https://youtu.be/mjYf-tD2SqM?t=539 ) there is a solution found to store values in AN, but it is… unnecessary complicated I think.

It would be super nice if maybe you could add such nodes to AN. I hope my descriptions are understandable and make sense. Anyway, again, thank you very much for AN+EN, e.g. the falloff tracer is super.

**Comment by Gerstmann-Bradley** [comment]
Talking about MIDI, shouldn't this issue/discussion located in https://github.com/JacquesLucke/animation_nodes/issues to discuss with Omar instead?

**Comment by Majoran99** [comment]
It is not essentially MIDI things. That was only my example. It would be generally about dealing with incoming dynamic data, also e.g. from a moving empty.

**Comment by Gerstmann-Bradley** [comment]
Still I think Omar should be involved in the discussion. Here this is just a fork from the main branch.

**Comment by 3DSinghVFX** [comment]
> What Blender/AN still lack are ways to filter / re-organise incoming data. This is especially an issue with sound input.
> For example: From a MIDI file I receive pitch 60 is going to 1 sometimes, remaining there for a few frames and then goes back to 0.
> I want every time it goes to 1 that an action (movement of an object) is triggered, no matter how long then it stays at 1. So only if a 1 is hit after being at 0 before, I want an object to do a movement.
> It would be great to have a node that registers such changes.
> 
> A related wish: For the duration of pitch 60 being at 1, I would like to have a counter counting up +1 every frame. Say, pitch 60 is normally at 0 but from frame 55 to 75 it is at 1, a counter should start counting on frame 55, until 75. (counter starts at 0, reaching 20.) The node should react on the fact that pitch 60 has hit 1 and stays there for 20 frames.
> 
> Next issue (related)… pitch 60 hits 1, an object should then be triggered to do something. Next time pitch 60 hits 1, another object should be triggered. So I would need a counter counting the 1-hits of pitch 60.
> (Related: a node that adds up every incoming value per frame.)

For this, I have to discuss with Omar because he added the MIDI.

> Also helpful would be: A node that registers whether an object is moving or not. Which means, the node compares the current location with the previous, whether it is the same or not.
>
> Next..: At some frames, a new random number should be generated. E.g. at frame 55, 100, 222 (or, every time pitch 60 hits 1). The random number would be for example new positions of an object. The problem at status quo is that I can pick out the 55 from the time info and then generate a random number, but it would not stay longer than frame 55. Of course, if I already know exactly that in frame 55, 100 and 222 there should be the new numbers, it is possible. But not flexible; when having a MIDI input I do not know when things happen.
> A node that stores a number would be super.

I think, all these things are possible with *Simulation Nodes* which are already in AN+EN.

> Helpful would also the possibility to compose object names. For example I have empty1, empty2, empty3… etc. and also cube1, cube2, cube3… A node that creates an object list with an number index list as input can be useful.

I think that is already possible in the [*Object Instancer* node](https://github.com/JacquesLucke/animation_nodes/issues/1286#issuecomment-580361537).

> I know that some of these things are _somehow_ realisable in AN, but it`s pretty a hack. For example in this Tut (https://youtu.be/mjYf-tD2SqM?t=539 ) there is a solution found to store values in AN, but it is… unnecessary complicated I think.

With the *Simulation Nodes*, It is also possible to create a group node to store values then you can use many times as you like. 

> It would be super nice if maybe you could add such nodes to AN. I hope my descriptions are understandable and make sense. Anyway, again, thank you very much for AN+EN, e.g. the falloff tracer is super.

@Majoran99 Thanks for your suggestions. It would be nice if you can create a separate proposal for each feature/node that is easy to follow and implement.

**Comment by Majoran99** [comment]
Thank you, 3DSinghVFX - in fact my issues are solvable with the simulation nodes. Sorry, I wasn't aware until now of the capabilities they have.
The one thing with composing a text, I will reformulate and open a separate proposal.
