### ISSUE TITLE
composing object names

### ISSUE THREAD

**Issue by Majoran99** [3DSinghVFX/animation_nodes#171]
![Image2](https://user-images.githubusercontent.com/82707686/118114339-bb87f980-b3e7-11eb-9193-cd73bd3828f8.jpg)

Say i have various objects in different collections or in no collection, they are just spread over my entire scene.
With a number here in the frame I would like to access them individually. You see in the viewer I can create an object name, but I cannot feed this data e.g. into Object Transforms Output as object name.
It would be great to have a "text2objectname" converter.
There is the "Filter Object List" which has a text input, but it requires the possible objects to be already in a list.

**Comment by Majoran99** [comment]
Solved - I found the "object by name" node. By chance... hard to find!

**Comment by 3DSinghVFX** [comment]
> Solved - I found the "object by name" node. By chance... hard to find!

Okay, good. Then, I'll close this issue.
