### ISSUE TITLE
Ability to Cache Simulation Node?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [3DSinghVFX/animation_nodes#172]
Wondering if it's possible / already doable.

**Comment by 3DSinghVFX** [comment]
> Wondering if it's possible / already doable.

Yes, it is possible. There is the option to cache the Group Node, so you can create Group Node with the Simulation Node.

![Screenshot from 2021-05-16 10-12-41](https://user-images.githubusercontent.com/30294746/118385738-4a3a8780-b62f-11eb-930c-cac97a98fcc1.png)

**Comment by Gerstmann-Bradley** [comment]
> > Wondering if it's possible / already doable.
> 
> Yes, it is possible. There is the option to cache the Group Node, so you can create Group Node with the Simulation Node.
> 
> ![Screenshot from 2021-05-16 10-12-41](https://user-images.githubusercontent.com/30294746/118385738-4a3a8780-b62f-11eb-930c-cac97a98fcc1.png)

Thanks! I just tried your method.
Taking Spline Trace as an example, If I set cache type to "Once", node tree becomes non-functional.
If I set cache type to the "Once per Frame", the node tree is functioning, but in the second round the node starts from 0 and won't function anymore.
If I set cache type to "Once per Input", it says cache method is not available...
Also one thing is that, I don't visualize anything signal on timeline as I can see in physics or other simulation.
I am not sure if my cache is generated properly or not.

Do you have any solution? Thanks!

**Comment by 3DSinghVFX** [comment]
> Taking Spline Trace as an example, If I set cache type to "Once", node tree becomes non-functional.

[One Time](https://docs.animation-nodes.com/documentation/subprograms/invoke/#one-time): it only computes that node-tree/group node once so that is why the tree is non-functional for another time.

> If I set cache type to the "Once per Frame", the node tree is functioning, but in the second round the node starts from 0 and won't function anymore.

[Once per Frame](https://docs.animation-nodes.com/documentation/subprograms/invoke/#once-per-frame).

What do you mean by the second round?

> If I set cache type to "Once per Input", it says cache method is not available...

[Once per Input](https://docs.animation-nodes.com/documentation/subprograms/invoke/#once-per-input): It is only available for input data types that are comparable.

> Also one thing is that, I don't visualize anything signal on timeline as I can see in physics or other simulation.
> I am not sure if my cache is generated properly or not.

I do not know is there a way to show per node cache in the timeline. I'll talk to Omar about this.

> Do you have any solution? Thanks!

Can you elaborate on your node tree for *Simulation Nodes*?

**Comment by Gerstmann-Bradley** [comment]
> What do you mean by the second round?

If everything is cached, then I need to play the cached animation correct?
So the timeline will be run again. But then there's nothing happening.

> Can you elaborate on your node tree for Simulation Nodes?

I guess my problem is solved.
I found the Curve Object Output Node needs to stand outside the cache so that the cache will work.
Generally the reason I am asking for cache is the lagging of viewport is horrible. Once cached, fps jumps from 6 fps to 20+ fps for this setup now.
Thanks for helping.
![image](https://user-images.githubusercontent.com/55994236/118449825-83233c80-b6c1-11eb-972e-9ab6f580054a.png)

**Comment by 3DSinghVFX** [comment]
Okay. Caching does not for any object in the Group/Loop node.
