### ISSUE TITLE
Performance of the Simulation Nodes

### ISSUE THREAD

**Issue by 3DSinghVFX** [3DSinghVFX/animation_nodes#175]
Continue from: https://github.com/3DSinghVFX/animation_nodes/issues/174#issuecomment-851215427

@Gerstmann-Bradley I'm using Ubuntu 18.04 LTS and Blender 2.93, I'm getting 24FPS for the *Simulation Input* node as well as with *Simulation Output* node:
![Screenshot from 2021-06-01 10-05-36](https://user-images.githubusercontent.com/30294746/120267279-46f6fb00-c2c1-11eb-94cb-331f73f1911b.png)

![Screenshot from 2021-06-01 10-07-56](https://user-images.githubusercontent.com/30294746/120267302-4fe7cc80-c2c1-11eb-87b9-b203469d4dbb.png)

**Comment by Gerstmann-Bradley** [comment]
that's nice. I'm not sure the reason then. I can only tell that i'm on windows 10.

**Comment by 3DSinghVFX** [comment]
> that's nice. I'm not sure the reason then. I can only tell that i'm on windows 10.

Okay. I'll look into that, and I'll also ask someone for Mac OS as well.

**Comment by Gerstmann-Bradley** [comment]
> > that's nice. I'm not sure the reason then. I can only tell that i'm on windows 10.
> 
> Okay. I'll look into that, and I'll also ask someone for Mac OS as well.

I guess I have found out the reason, but it's little difficult for me to understand why it happens exactly.
Would you please try this file to see the FPS?
The problem is there are some node tree that contains lots of group node and loop node.
These aren't being executed. Nevertheless their presence seems to impact simulation node somehow.
If I remove these node trees, FPS goes back to 30.

[Simulation BUG.zip](https://github.com/3DSinghVFX/animation_nodes/files/6573447/Simulation.BUG.zip)

**Comment by OmarEmaraDev** [comment]
This is due to expensive searches of nodes. Might be redundant, we will need to investigate this further. Not time at the moment, but here is a flamegraph.

![Flamegraph](https://user-images.githubusercontent.com/25300994/120366631-2b671100-c310-11eb-85db-f7943ab69435.png)

**Comment by 3DSinghVFX** [comment]
> This is due to expensive searches of nodes. Might be redundant, we will need to investigate this further. Not time at the moment, but here is a flamegraph.
> 
> ![Flamegraph](https://user-images.githubusercontent.com/25300994/120366631-2b671100-c310-11eb-85db-f7943ab69435.png)

@OmarEmaraDev Thanks. One thing I would like to add is that, if a node-tree has a large number of nodes and visible while playing animation, it also drops the FPS. Is that also related to *searches of nodes*?

**Comment by OmarEmaraDev** [comment]
@3DSinghVFX No. It takes time to draw those nodes on the screen, so each visible node adds to the render time and reduces FPS.

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX No. It takes time to draw those nodes on the screen, so each visible node adds to the render time and reduces FPS.

Okay.

**Comment by Gerstmann-Bradley** [comment]
I think this post should be set "Pending". Since this an issue that's not being investigated for the moment.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Can you create an issue in the main repository so that we can track it better?
