### ISSUE TITLE
Proposal: Introduce complex numbers to Animation Nodes

### ISSUE THREAD

**Issue by meikasahara** [3DSinghVFX/animation_nodes#177]
Now that you have included dedicated nodes for converting various data types to and from numpy arrays, it would be possible to extend these nodes to include complex numbers and complex arrays. I have included a screenshot of how this can be implemented using the expression node. Using the cmath library as well as numpy, numeric manipulation of complex numbers is possible. 
![complex_lists_AN](https://user-images.githubusercontent.com/29499027/120767729-224e8d80-c524-11eb-9076-cbbf54e56182.png)

**Comment by 3DSinghVFX** [comment]
@meikasahara Thanks for the feedback. In *Numpy Nodes* you have 2D vector list that can be used for complex numbers. Anyway, I'll look into this.

**Comment by meikasahara** [comment]
Sure complex numbers can be represented as 2d vectors, the only difference is the complex conjugation (and the fact that 1j*1j=-1) that does not occur under the usual vector operations. Thanks!
