### ISSUE TITLE
Python version mismatch

### ISSUE THREAD

**Issue by gogobd** [3DSinghVFX/animation_nodes#178]
Hi! I'm using Blender 2.93.0 (release) on macOS, and it uses Python 3.9 however animation nodes is compiled for Python 3.7 (mac) - so the addon won't install.

<img width="772" alt="Screenshot 2021-06-09 at 22 52 36" src="https://user-images.githubusercontent.com/728976/121427849-78349280-c975-11eb-8b51-47eb2d50fb55.png">

**Comment by Gerstmann-Bradley** [comment]
Please download from here as indicated by the image:
https://github.com/3DSinghVFX/animation_nodes/releases
![image](https://user-images.githubusercontent.com/55994236/121429395-ddbc5b00-c944-11eb-8f8c-7a912c2ad765.png)

**Comment by gogobd** [comment]
I also found it here: https://blender.community/c/graphicall/phbbbc/ But the releases on *this* project don't have Python 3.9 (I know it's not a bug, it's just a bit inconvenient).

**Comment by 3DSinghVFX** [comment]
> I also found it here: https://blender.community/c/graphicall/phbbbc/ But the releases on _this_ project don't have Python 3.9 (I know it's not a bug, it's just a bit inconvenient).

Hi. I have checked that, it is for Python 3.9. Did you remove the old version of Animation Nodes?

**Comment by gogobd** [comment]
The download from https://blender.community/c/graphicall/phbbbc/ worked for me, and it's Animation Nodes PLUS Extra Nodes which is exactly what I was looking for. I did not have to remove the old version because it was a fresh install of 2.93.0 release.

**Comment by gogobd** [comment]
I suppose this will be resolved with the next release given it's already available as pre-release. I'm closing this issue, thanks!
