### ISSUE TITLE
Python version mismatch - Blender 2.93

### ISSUE THREAD

**Issue by kurnikoff** [3DSinghVFX/animation_nodes#179]
Hi!

I just updated Blender to 2.93 and can't use Animation Nodes any more. When I try to enable it in Add Ons, I get this message.

<img width="772" alt="Screenshot 2021-06-10 at 14 16 12" src="https://user-images.githubusercontent.com/62060035/121531591-78c13d80-c9f6-11eb-9a32-c194991b5706.png">

Any chance you could please compile it with Python 3.9.2 please - I can't seem to do it myself from Termina.

Thanks

**Comment by Gerstmann-Bradley** [comment]
Please download from here as indicated by the image:
https://github.com/3DSinghVFX/animation_nodes/releases
![image](https://user-images.githubusercontent.com/55994236/121532316-3a635880-c9cd-11eb-8455-48baaa7a1f77.png)

**Comment by kurnikoff** [comment]
> Please download from here as indicated by the image:
> https://github.com/3DSinghVFX/animation_nodes/releases
> ![image](https://user-images.githubusercontent.com/55994236/121532316-3a635880-c9cd-11eb-8455-48baaa7a1f77.png)

I have still the same issue - I can install it without problem, but when I click to enable the Add-on, I get the Error screen.

**Comment by Gerstmann-Bradley** [comment]
Have you manually remove the old AN?

**Comment by kurnikoff** [comment]
I think issue is fixed now. I downloaded [this version of AN](https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build) and I managed to instal and enable it now without problems. 

I tested it by duplicating cube with AN add on and it looks like it works now :)
