### ISSUE TITLE
Seconds and minutes

### ISSUE THREAD

**Issue by DinkoDesign** [3DSinghVFX/animation_nodes#180]
Hi! - I am a total beginner in Blender, so be kind!

What I am struggling with is to make a digital clock / countdown with hours, minutes and seconds. Now it counts everything to 100 and not 60. Is there a clever way to do this?
My task is to make an animation of a product that needs a 24 hour visual timer, with hrs, minutes and seconds.
The way I have to do it now, is to make each of them count accordingly in separate text objects, then loop keyframes of the seconds and minutes to fill up the 24 hour cycle.

**Comment by meikasahara** [comment]
![image](https://user-images.githubusercontent.com/29499027/121652671-8e8d3c00-caa4-11eb-84ff-7e094f4ea928.png)

**Comment by meikasahara** [comment]
![image](https://user-images.githubusercontent.com/29499027/121660435-eed3ac00-caab-11eb-8ef6-09f2c697e12e.png)

**Comment by DinkoDesign** [comment]
Thanks! I also found this on Youtube: https://www.youtube.com/watch?v=-5ffLCoEq2E
