### ISSUE TITLE
Question: Animated object location

### ISSUE THREAD

**Issue by gogobd** [3DSinghVFX/animation_nodes#181]
Hi! I have a question: I created two empties, one parented to the other. The parent is animated and rotates. How can I get the actual location of the child object?

**Comment by Gerstmann-Bradley** [comment]
You need to use **"Object Matrix input"**, and then you may **"Decompose Matrix"** into Location, Rotation and Scale for control. Or you may use Matrix directly with relative nodes, such as Offset Matrix, Matrix Math, etc.

**Comment by gogobd** [comment]
Thank you @Gerstmann-Bradley that's exactly what I was missing!
