### ISSUE TITLE
There is no Get Custom Attribute option under Object menu

### ISSUE THREAD

**Issue by mhzhao** [3DSinghVFX/animation_nodes#182]
I'm using Blender 2.93.5 macOS version, I install the latest version of the animation_nodes with extra nodes from here, I find that there may be a mixed wrong version of Set/Get Custom Attribute under Object and Mesh. There is only Set Custom Attribute under Object as shown in the picture.
![Screen Shot 2021-10-29 at 23 43 11](https://user-images.githubusercontent.com/19246396/139520486-07f639e8-8bb3-403a-99df-6824aa32199f.png)
 While there are Set/Get Custom Attribute, but the Set Custom Attribute seems not correct? As shown in the picture.
![Screen Shot 2021-10-29 at 23 46 17](https://user-images.githubusercontent.com/19246396/139520547-060a25ee-cc63-49cc-b74b-aae0120857c4.png)

My guess is that they are confused because they have the same name/id in the code? so they are put in wrong place?

**Comment by mhzhao** [comment]
I check a little bit the source code, it looks the Set Custom Attribute under Object is copied from Mesh? There are minor differences, I think line 76 should be comment out because here is object?
![image](https://user-images.githubusercontent.com/19246396/139522284-01eea8b1-cbe0-4219-ab93-3787257c1962.png)

**Comment by 3DSinghVFX** [comment]
I have removed the OLD *Set Custom Attribute* node https://github.com/3DSinghVFX/animation_nodes/commit/4efbbade146926c7beacd14ea52e57ca1c51a845

I think you want to set the custom attributes for the Curve object which is not supported in Blender 3.0.

**Comment by mhzhao** [comment]
Okay, I noticed this because I watched your this tutorial https://www.youtube.com/watch?v=BjrUUX7NW1Y&t=50s&ab_channel=3DSinghVFX where you mentioned the Set Custom Attribute under Object

**Comment by 3DSinghVFX** [comment]
> Okay, I noticed this because I watched your this tutorial https://www.youtube.com/watch?v=BjrUUX7NW1Y&t=50s&ab_channel=3DSinghVFX where you mentioned the Set Custom Attribute under Object

Yes, you are right, the old version of these nodes takes Object (Mesh) as input. However, you can do the same operations with the new nodes as well. Now, the Get and Insert Custom Attribute nodes take Mesh as input.

**Comment by mhzhao** [comment]
I think this is really great idea to use Set/Get Custom Attribute to communicate among AN nodes, Shader nodes and Geometry nodes. Since now they are only applied to Mesh, is any way to take information from AN node data to shader node for splines or others? The scenario for me is that I want to use sound spectrum data from AN node to change the curve colors in the shader node. 
![image](https://user-images.githubusercontent.com/19246396/139568972-fee6399d-947b-494a-9d08-9c3e8f9d1420.png)

**Comment by 3DSinghVFX** [comment]
@mhzhao Actually, that is not possible for Splines. However, you can convert them into Mesh tubes then transfer any kind of data to the Shader nodes (Blender 2.93):
![Screenshot from 2021-10-31 13-15-16](https://user-images.githubusercontent.com/30294746/139606084-94b4fbe6-0249-4092-8007-08274b1e0b1a.png)

Blend File: 
[Line_Mesh_with_Color1.zip](https://github.com/3DSinghVFX/animation_nodes/files/7449974/Line_Mesh_with_Color1.zip)

**Comment by mhzhao** [comment]
Look nice and neat. Thank you.
