### ISSUE TITLE
Python 3.10 builds

### ISSUE THREAD

**Issue by meikasahara** [3DSinghVFX/animation_nodes#184]
With Blender 3.2 alpha moving to python 3.10, could you provide python 3.10 builds of animation nodes extra? Thank you in advance!

**Comment by meikasahara** [comment]
The newest builds are in the Releases section in ExtraNodes Latest, despite displaying an old date. 

https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build

**Comment by 3DSinghVFX** [comment]
> The newest builds are in the Releases section in ExtraNodes Latest, despite displaying an old date.
> 
> https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build

Yes, it is.
