### ISSUE TITLE
Compiling with python 3.11

### ISSUE THREAD

**Issue by meikasahara** [3DSinghVFX/animation_nodes#190]
As it currently stands, the python setup file works only with python 3.10. When trying to compile it using python 3.11, as required by the newest 4.1 alpha blender builds that are built on python3.11, the compilation process halts with cython errors. Could you make the code compatible with python 3.11 and/or provide additional python3.11 pre-compiled of the add-on? Thank you!

**Comment by 3DSinghVFX** [comment]
Hi.
Sorry for the late reply. Could please provide the Error report? I'll look into that.

**Comment by meikasahara** [comment]
I have included the terminal output of 
`python3.11 setup.py build --noversioncheck --export`
 
[output.txt](https://github.com/3DSinghVFX/animation_nodes/files/14022310/output.txt)

**Comment by 3DSinghVFX** [comment]
Have you tried the clean build?
`python3.11 setup.py clean`
then build
`python3.11 setup.py build --export --noversioncheck`

BTW have you checked the Cython version?

**Comment by meikasahara** [comment]
I tried the clean build and then build using the above commands but errors still appear. The installed Cython version on my system is 0.29.28

**Comment by 3DSinghVFX** [comment]
Okay, then you need to update the Cython version 3.0.

**Comment by meikasahara** [comment]
Indeed, that was the case! I had to make sure that python3.11 used the new version of cython through pip. It now compiles successfully and the build works on blender 4.1. Thanks!
