### ISSUE TITLE
Invalid "Layer Index" parameter on "GPencil Object Input" causes crash

### ISSUE THREAD

**Issue by df-0** [3DSinghVFX/animation_nodes#71]
Setting GPencil Object Input's "Layer Index" parameter to a nonexistent layer instantly crashes Blender 2.81 on MacOS. This happens every time on my machine.

I've also (probably relatedly?) had a crash when I added a new layer to a grease pencil object via the blender interface, although that doesn't seem to happen every time.

**Comment by 3DSinghVFX** [comment]
Hi...
I have checked on Blender (2.81-2.83) (Ubuntu 16.04), it is working fine. Have you tried *Name* (Available in N-panel) option instead of *Layer Index* in *GPencil Object Input* node? Can you please provide the screenshot of the terminal of the blender crashed?

**Comment by df-0** [comment]
Just tested this on Windows 10, Blender 2.81, works fine as far as I can see. Will check again on MacOs when I get a chance!

**Comment by 3DSinghVFX** [comment]
Okay.

**Comment by 3DSinghVFX** [comment]
@df-0 I have reworked the Grease Pencil nodes _(base grease pencil nodes also added in the AN)_, please try the latest version of AN+EN (or AN).

Please report if you still experience the issue.

**Comment by df-0** [comment]
Seems to be working now, on Blender 2.82 (2.82 2020-02-12), MacOS 10.15.3 (19D76). Tried various things and couldn't get it to crash :-)
