### ISSUE TITLE
"Interpolation from Curve" always returning a value of 0 (zero)

### ISSUE THREAD

**Issue by 8BitsGotBite** [3DSinghVFX/animation_nodes#72]
Even the standard linear curve shows up as flat in the viewer.

![Screenshot 2020-01-21 17 21 03](https://user-images.githubusercontent.com/40199415/72822900-26517680-3c73-11ea-9014-137bd51d0004.png)

**Comment by Gerstmann-Bradley** [comment]
I have reported the same bugs in #1261. 
According to Omar it's "to accommodate the API change, that meant older versions will no longer work. You can revert a51e572 temporarily until you choose to update."
In short, using new version of blender will fix this issue.

**Comment by 8BitsGotBite** [comment]
Thank you. Did not realize there were API changes in the newer Blender version. Will give 2.82 beta a spin then :).

**Comment by 3DSinghVFX** [comment]
Thanks, @Gerstmann-Bradley for answering. 

@8BitsGotByte use Blender version 2.82 or higher.

**Comment by 8BitsGotBite** [comment]
@3DSinghVFX Blender 2.82 fixes the problem. Issue can be closed. Ty

**Comment by 3DSinghVFX** [comment]
Okay.
